# Generated by Django 4.2.11 on 2024-12-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('password_change', 'Cambio de contraseña'), ('password_change_failed', 'Intento fallido de cambio de contraseña'), ('profile_update', 'Actualización de perfil'), ('failed_login', 'Intento fallido de inicio de sesión'), ('user_created', 'Usuario creado'), ('user_updated', 'Usuario actualizado'), ('user_deleted', 'Usuario eliminado'), ('token_validation', 'Token validado'), ('token_validation_failed', 'Token inválido'), ('profile_fetch', 'Obtención de perfil'), ('profile_fetch_failed', 'Error al obtener perfil')], max_length=50),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
