# Generated by Django 4.2.11 on 2024-12-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('api', '0002_alter_useractivitylog_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivitylog',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='companies.company'),
        ),
    ]
